Repository shoooong/Auction-Front, pull requests merged in 2024-07, with the labels that each got.

#10 Front / 로그인 시 권한 확인 후 관리자 경로 이동 설정
  front/src/pages/user/Login.jsx
Labels: enhancement

#11 feat_luckydraw 페이지생성
  front/src/hooks/useLuckyDraw.jsx
  front/src/layout/MainCategory.jsx
  front/src/pages/draw/Draw.jsx
  front/src/pages/draw/LuckyDraw.jsx
  front/src/router/mainRouter.jsx
Labels: enhancement

#13 Front / 럭키드로우 axios 연결 및 응모하기 구현
  front/src/pages/draw/LuckyDraw.jsx
  front/src/pages/draw/LuckyDrawDetail.jsx
  front/src/router/luckyDrawRouter.jsx
  front/src/router/mainRouter.jsx
Labels: 🖥️ FrontEnd, ✨ FEAT

#16 Front / 다음 우편번호 API 구현중
  front/src/api/user/kakaoMapsApi.jsx
Labels: 🖥️ FrontEnd, ✨ FEAT

#17 Dev
  front/src/api/user/kakaoMapsApi.jsx
  front/src/pages/draw/LuckyDraw.jsx
  front/src/pages/draw/LuckyDrawDetail.jsx
  front/src/pages/user/KakaoRedirect.jsx
  front/src/pages/user/Login.jsx
  front/src/router/luckyDrawRouter.jsx
  front/src/router/mainRouter.jsx
Labels: 🖥️ FrontEnd

#18 Dev
  front/package-lock.json
  front/package.json
  front/src/layout/Footer.jsx
  front/src/pages/Alarm.jsx
  front/src/pages/admin/AdminProducts.jsx
  front/src/pages/admin/layout/CommonList.jsx
  front/src/pages/admin/layout/UserProfile.jsx
  front/src/router/mypageRouter.jsx
  front/src/router/root.jsx
  front/src/styles/index.css
Labels: 🖥️ FrontEnd, 💡cicd

#19 Front / 럭키드로우 메인,상세 css 작업중
  front/src/pages/draw/LuckyDraw.jsx
  front/src/pages/draw/LuckyDrawDetail.jsx
  front/src/styles/luckydraw.css
Labels: 🖥️ FrontEnd

#20 Front / chore SERVER_URL 사용 절대 경로로 수정
  front/src/hooks/useLuckyDraw.jsx
  front/src/pages/draw/LuckyDraw.jsx
  front/src/store/slices/loginSlice.jsx
Labels: 🖥️ FrontEnd, 🛠FIX

#21 Front / feat : 럭키드로우 응모 남은 시간 및 css 추가
  front/src/pages/draw/LuckyDrawDetail.jsx
  front/src/styles/luckydraw.css
Labels: 🖥️ FrontEnd, ✨ FEAT

#22 Front / feat : 미로그인시 응모 불가 및 로그인 페이지로 이동
  front/src/pages/draw/LuckyDrawDetail.jsx
Labels: 🖥️ FrontEnd, ✨ FEAT

#23 Dev
  front/Dockerfile
  front/src/hooks/useLuckyDraw.jsx
  front/src/pages/draw/LuckyDraw.jsx
  front/src/pages/draw/LuckyDrawDetail.jsx
  front/src/store/slices/loginSlice.jsx
  front/src/styles/luckydraw.css
Labels: 🖥️ FrontEnd, 💡cicd

#25 front/ admin 화면구성 및 api 호출 완료
  front/src/api/admin/AdminLuckyApi.js
  front/src/api/admin/productApi.js
  front/src/api/admin/requestApi.js
  front/src/pages/admin/AdminLuckydraws.jsx
  front/src/pages/admin/AdminProductDetailed.jsx
  front/src/pages/admin/AdminProducts.jsx
  front/src/pages/admin/AdminRequest.jsx
  front/src/pages/admin/AdminRequestDetailed.jsx
  front/src/pages/admin/LuckyDrawForm.jsx
  front/src/pages/admin/layout/AdminSideBar.jsx
  front/src/pages/admin/layout/CommonList.jsx
  front/src/pages/admin/layout/RequestModal.jsx
  front/src/pages/admin/layout/UserProfile.jsx
  front/src/router/AdminRouter.jsx
  front/src/router/mainRouter.jsx
  front/src/router/root.jsx
Labels: 🖥️ FrontEnd, ✨ FEAT

#26 Dev
  front/Dockerfile
  front/src/api/admin/AdminLuckyApi.js
  front/src/api/admin/productApi.js
  front/src/api/admin/requestApi.js
  front/src/pages/admin/AdminLuckydraws.jsx
  front/src/pages/admin/AdminProductDetailed.jsx
  front/src/pages/admin/AdminProducts.jsx
  front/src/pages/admin/AdminRequest.jsx
  front/src/pages/admin/AdminRequestDetailed.jsx
  front/src/pages/admin/LuckyDrawForm.jsx
  front/src/pages/admin/layout/AdminSideBar.jsx
  front/src/pages/admin/layout/CommonList.jsx
  front/src/pages/admin/layout/RequestModal.jsx
  front/src/pages/admin/layout/UserProfile.jsx
  front/src/router/AdminRouter.jsx
  front/src/router/mainRouter.jsx
  front/src/router/root.jsx
Labels: 🖥️ FrontEnd, 💡cicd

#27 Front / Dockerfile 경로 수정
  front/Dockerfile
Labels: 🖥️ FrontEnd, 🛠FIX, 💡cicd

#29 Front / Dockerfile 수정
  front/Dockerfile
Labels: 🖥️ FrontEnd, 🛠FIX, 💡cicd

#30 Front / Dockerfile 수정 test
  front/Dockerfile
Labels: 🖥️ FrontEnd, 🛠FIX, 💡cicd

#31 Front / Dockerfile pwd 확인
  front/Dockerfile
Labels: 🖥️ FrontEnd, 🛠FIX, 💡cicd

#32 Front / Dockerfile 경로확인
  front/Dockerfile
Labels: 🖥️ FrontEnd, 🛠FIX, 💡cicd

#33 Front / 위치변경
  front/Dockerfile
Labels: 🖥️ FrontEnd, 🛠FIX, 💡cicd

#34 Front / Dockerfile, nginx.conf
  front/Dockerfile
  front/nginx.conf
Labels: 🖥️ FrontEnd, Config, 🛠FIX, 💡cicd

#35 Front / feat : 마이페이지 메인 서버와 연결 및 css 진행중
  front/src/assets/images/icon1.jpg
  front/src/assets/images/icon2.jpg
  front/src/assets/images/icon4.jpg
  front/src/assets/images/icon5.jpg
  front/src/assets/images/icon6.jpg
  front/src/assets/images/myson.jpg
  front/src/pages/user/MypageMain.jsx
  front/src/router/mypageRouter.jsx
  front/src/styles/mypage.css
Labels: 🖥️ FrontEnd, ✨ FEAT

#36 Front / feat : 마이페이지 구매 내역 및 패키지 구조 변경
  front/src/pages/user/mypage/BuyHistory.jsx
  front/src/pages/user/mypage/MypageMain.jsx
  front/src/router/mypageRouter.jsx
  front/src/styles/mypage.css
Labels: 🖥️ FrontEnd, Config, ✨ FEAT

#39 Front / feat : 마이페이지 jwtAxios 사용하여 api 분리
  front/src/api/user/mypageApi.jsx
  front/src/pages/user/mypage/BuyHistory.jsx
  front/src/pages/user/mypage/MypageMain.jsx
  front/src/pages/user/mypage/SaleHistory.jsx
Labels: 🖥️ FrontEnd, 🛠FIX

#40 Front / feat : 마이페이지 관심상품
  front/src/api/user/mypageApi.jsx
  front/src/components/mypage/MypageBookmark.jsx
  front/src/pages/user/mypage/BookmarkProduct.jsx
  front/src/router/mypageRouter.jsx
  front/src/styles/bookmark.css
Labels: 🖥️ FrontEnd, ✨ FEAT

#41 Front / feat : 마이페이지 응모 내역
  front/src/api/user/mypageApi.jsx
  front/src/pages/user/mypage/DrawHistory.jsx
  front/src/router/mypageRouter.jsx
  front/src/styles/mypage.css
Labels: 🖥️ FrontEnd, ✨ FEAT

#42 Front / feat : 마이페이지 계좌 관리 서버 연결
  front/src/api/user/mypageApi.jsx
  front/src/pages/user/mypage/Account.jsx
  front/src/router/mypageRouter.jsx
Labels: 🖥️ FrontEnd, ✨ FEAT

#43 Front / feat : 마이페이지 아이콘 수정
  front/src/assets/images/icon1.jpg
  front/src/assets/images/icon1.svg
  front/src/assets/images/icon2.jpg
  front/src/assets/images/icon2.svg
  front/src/assets/images/icon3.svg
  front/src/assets/images/icon4.jpg
  front/src/assets/images/icon4.svg
  front/src/assets/images/icon5.jpg
  front/src/assets/images/icon5.svg
  front/src/assets/images/icon6.jpg
  front/src/assets/images/icon6.svg
  front/src/pages/user/mypage/MypageMain.jsx
  front/src/styles/mypage.css
Labels: 🖥️ FrontEnd, ✨ FEAT

#45 Front / feat : 마이페이지 프로필 관리 css 진행중
  front/src/pages/user/mypage/BookmarkProduct.jsx
  front/src/pages/user/mypage/Modify.jsx
  front/src/pages/user/mypage/MypageMain.jsx
  front/src/styles/mypage.css
Labels: 🖥️ FrontEnd, ✨ FEAT

#46 front/admin 진행중
  front/src/api/admin/AdminLuckyApi.js
  front/src/api/admin/productApi.js
  front/src/api/admin/requestApi.js
  front/src/pages/admin/AdminProductDetailed.jsx
  front/src/pages/admin/AdminProducts.jsx
  front/src/pages/admin/AdminRequest.jsx
  front/src/pages/admin/layout/AdminLayout.jsx
  front/src/pages/admin/layout/CommonList.jsx
Labels: 🖥️ FrontEnd

#48 Front / feat : 럭키드로우 api 요청 코드 분리
  front/src/api/luckydrawApi.jsx
  front/src/hooks/useLuckyDraw.jsx
  front/src/pages/draw/LuckyDrawDetail.jsx
Labels: 🖥️ FrontEnd, ✨ FEAT

#49 Front / style : className='title' 사용해서 타이틀 css 수정
  front/src/pages/user/mypage/Account.jsx
  front/src/pages/user/mypage/Address.jsx
  front/src/pages/user/mypage/BuyHistory.jsx
  front/src/pages/user/mypage/DrawHistory.jsx
  front/src/pages/user/mypage/Modify.jsx
  front/src/pages/user/mypage/SaleHistory.jsx
Labels: 🖥️ FrontEnd

#51 Front / fix : List타입 Dto map 사용시 key 설정 누락 수정
  front/src/pages/user/mypage/BuyHistory.jsx
  front/src/pages/user/mypage/SaleHistory.jsx
Labels: 🖥️ FrontEnd, 🛠FIX

#52 Front / feat : 마이페이지 관심 탭 변경
  front/src/components/mypage/MypageBookmark.jsx
  front/src/styles/mypage.css
Labels: 🖥️ FrontEnd

#55 Front / fix : 배송지 요청 실패 문제 해결, 새로 추가 시 화면에 바로 보이도록 상태 추가
  front/src/pages/user/jwtUtil.js
  front/src/pages/user/mypage/Address.jsx
Labels: 🖥️ FrontEnd, 🛠FIX

#56 Dev
  front/src/api/user/userApi.jsx
  front/src/assets/images/bumsu.svg
  front/src/assets/images/selkiAvatar copy.svg
  front/src/hooks/useCustomRegister.jsx
  front/src/pages/admin/AdminLuckydraws.jsx
  front/src/pages/admin/AdminMain.jsx
  front/src/pages/admin/AdminProducts.jsx
  front/src/pages/admin/AdminRegister.jsx
  front/src/pages/admin/AdminRequest.jsx
  front/src/pages/admin/layout/UserProfile.jsx
  front/src/pages/user/jwtUtil.js
  front/src/pages/user/mypage/Address.jsx
  front/src/router/AdminRouter.jsx
Labels: 🖥️ FrontEnd, Config, ✨ FEAT, 🛠FIX, 💡cicd

#57 Front / feat : 마이페이지 배송지 삭제 기능 추가
  front/src/api/user/mypageApi.jsx
  front/src/pages/user/mypage/Address.jsx
Labels: 🖥️ FrontEnd, ✨ FEAT

#60 Front / 포트 수정
  front/Dockerfile
Labels: 🖥️ FrontEnd, 🛠FIX, 💡cicd

#61 Dev
  front/nginx.conf
  front/package-lock.json
  front/package.json
  front/src/hooks/useCouponEvent.jsx
  front/src/hooks/useUserCoupon.jsx
  front/src/pages/event/Event.jsx
  front/src/pages/serviceCenter/inquiry/AdminInquiryDetail.jsx
  front/src/pages/serviceCenter/inquiry/AdminInquiryListContainer.jsx
  front/src/pages/serviceCenter/inquiry/InquiryDetail.jsx
  front/src/pages/serviceCenter/inquiry/InquiryListContainer.jsx
  front/src/pages/serviceCenter/inquiry/InquiryRegistration.jsx
  front/src/pages/serviceCenter/notice/AdminNotice.jsx
  front/src/pages/serviceCenter/notice/AdminNoticeDetail.jsx
  front/src/pages/serviceCenter/notice/AdminNoticeDetailContainer.jsx
  front/src/pages/serviceCenter/notice/AdminNoticeList.jsx
  front/src/pages/serviceCenter/notice/NoticeDetail.jsx
  front/src/pages/serviceCenter/notice/NoticeDetailContainer.jsx
  front/src/pages/serviceCenter/notice/NoticeDetailContent.jsx
  front/src/pages/serviceCenter/notice/NoticeEditForm.jsx
  front/src/pages/serviceCenter/notice/NoticeList.jsx
  front/src/pages/serviceCenter/notice/NoticeRegistration.jsx
  front/src/pages/serviceCenter/notice/NoticeRegistrationForm.jsx
  front/src/pages/shop/Shop.jsx
  front/src/pages/style/FeedBookmarkContainer.jsx
  front/src/pages/style/StyleRegistration.jsx
  front/src/pages/user/mypage/coupon.jsx
  front/src/router/mainRouter.jsx
  front/src/router/mypageRouter.jsx
  front/src/router/serviceRouter.jsx
  front/src/styles/sub.css
Labels: 🖥️ FrontEnd, ✨ FEAT, 🛠FIX, 💡cicd

#62 Dev
  front/src/api/admin/AdminLuckyApi.js
  front/src/api/admin/productApi.js
  front/src/api/admin/requestApi.js
  front/src/pages/Rank/StyleRankingList.jsx
  front/src/pages/admin/AdminProducts.jsx
  front/src/pages/admin/AdminRequest.jsx
  front/src/pages/admin/admin.css
  front/src/pages/admin/layout/AdminFooter.jsx
  front/src/pages/admin/layout/AdminLayout.jsx
  front/src/pages/admin/layout/AdminSideBar.jsx
  front/src/pages/admin/layout/CommonList.jsx
  front/src/pages/admin/layout/UserProfile.jsx
  front/src/pages/product/NewProduct.jsx
  front/src/pages/product/PopularProductList.jsx
  front/src/pages/product/TopProduct.jsx
  front/src/pages/serviceCenter/notice/AdminNoticeList.jsx
  front/src/pages/serviceCenter/notice/NoticeDetailContent.jsx
  front/src/router/AdminRouter.jsx
  front/src/router/serviceRouter.jsx
  front/src/serviceCenter/notice/NoticeDetail.jsx
  front/src/serviceCenter/notice/NoticeList.jsx
Labels: 🖥️ FrontEnd, Config, ⚙️ REFACTOR, 🛠FIX, 💡cicd

#63 Dev
  front/.env.development
  front/.env.production
  front/package-lock.json
  front/package.json
  front/src/pages/serviceCenter/inquiry/AdminInquiryDetail.jsx
  front/src/pages/serviceCenter/inquiry/AdminInquiryDetailPage.jsx
  front/src/pages/serviceCenter/inquiry/AdminInquiryItemList.jsx
  front/src/pages/serviceCenter/inquiry/InquiryDetail.jsx
  front/src/pages/serviceCenter/inquiry/InquiryDetailPage.jsx
  front/src/pages/serviceCenter/notice/AdminNotice.jsx
  front/src/pages/serviceCenter/notice/AdminNoticeList.jsx
  front/src/pages/serviceCenter/notice/NoticeRegistration.jsx
  front/src/pages/serviceCenter/notice/NoticeRegistrationForm.jsx
  front/src/router/AdminRouter.jsx
  front/src/router/serviceRouter.jsx
  front/src/serviceCenter/inquiry/Inquiry.jsx
  front/src/serviceCenter/inquiry/InquiryItem.jsx
  front/src/serviceCenter/inquiry/InquiryRegistration.jsx
  front/src/serviceCenter/notice/NoitceTab.jsx
  front/src/serviceCenter/notice/Notice.jsx
  front/src/serviceCenter/notice/NoticeDetail.jsx
  front/src/serviceCenter/notice/NoticeItem.jsx
  front/src/serviceCenter/notice/NoticeList.jsx
Labels: 🖥️ FrontEnd, Config, 💡cicd

#64 Front / app test
  front/src/App.js
Labels: 🖥️ FrontEnd, 💡cicd

#65 Front / 원복
  front/.env.development
  front/.env.production
  front/package-lock.json
  front/package.json
Labels: 🖥️ FrontEnd, 🛠FIX, 💡cicd

#66 Front / 원복
  front/package-lock.json
  front/package.json
  front/src/App.js
Labels: 🖥️ FrontEnd, Config, 💡cicd

#67 Dev
  front/src/pages/style/StyleRegistration.jsx
  front/src/router/mainRouter.jsx
Labels: 🖥️ FrontEnd, 💡cicd

#68 front/admin 수정중
  front/src/api/admin/AdminLuckyApi.js
  front/src/api/admin/productApi.js
  front/src/api/admin/requestApi.js
  front/src/pages/admin/AdminProducts.jsx
  front/src/pages/admin/AdminRequestDetailed.jsx
  front/src/pages/admin/admin.css
  front/src/pages/admin/layout/AdminSideBar.jsx
  front/src/pages/admin/layout/CommonList.jsx
  front/src/router/AdminRouter.jsx
Labels: 🖥️ FrontEnd

#70 Feat history
  front/src/api/user/mypageApi.jsx
  front/src/pages/user/mypage/BuyHistory.jsx
  front/src/pages/user/mypage/MypageMain.jsx
  front/src/pages/user/mypage/SaleHistory.jsx
  front/src/pages/user/mypage/buyHistory/BuyHistory.jsx
  front/src/pages/user/mypage/buyHistory/BuyHistoryComplete.jsx
  front/src/pages/user/mypage/buyHistory/BuyHistoryProcess.jsx
  front/src/pages/user/mypageUtil.js
  front/src/router/mypageRouter.jsx
Labels: 🖥️ FrontEnd, ✨ FEAT

#71 Feat cancel
  front/src/api/user/mypageApi.jsx
  front/src/pages/user/mypage/SaleHistory.jsx
  front/src/pages/user/mypage/buyHistory/BuyHistoryProcess.jsx
Labels: 🖥️ FrontEnd, ✨ FEAT

#74 front/request 수정
  front/src/api/admin/requestApi.js
  front/src/pages/admin/AdminRequestDetailed.jsx
Labels: 🖥️ FrontEnd

#75 Dev
  front/src/api/admin/requestApi.js
  front/src/pages/admin/AdminRequestDetailed.jsx
  front/src/pages/event/Event.jsx
  front/src/pages/shop/Shop.jsx
  front/src/styles/mypage.css
  front/src/styles/sub.css
  package-lock.json
Labels: 🖥️ FrontEnd, Config, ⚙️ REFACTOR, 💡cicd

#76 Front / feat : 배송지 수령인 정보 추가
  front/src/components/mypage/Postcode.jsx
  front/src/pages/user/mypage/Address.jsx
Labels: 🖥️ FrontEnd, ✨ FEAT

#77 Front / feat : 배송지 Dialog 추가 및 CSS 완료
  front/src/components/mypage/Postcode.jsx
  front/src/pages/user/mypage/Address.jsx
  front/src/pages/user/mypageUtil.js
  front/src/styles/mypage.css
  front/src/styles/postcode.css
Labels: 🖥️ FrontEnd, ✨ FEAT

#78 Front / feat : 배송지 핸드폰번호 유효성 검사 추가
  front/src/pages/user/mypage/Address.jsx
Labels: 🖥️ FrontEnd, ✨ FEAT

#79 Feat css
  front/src/assets/images/toss_banner.webp
  front/src/pages/draw/LuckyDrawDetail.jsx
  front/src/pages/user/mypage/Account.jsx
  front/src/pages/user/mypage/Address.jsx
  front/src/pages/user/mypage/DrawHistory.jsx
  front/src/pages/user/mypage/Modify.jsx
  front/src/pages/user/mypage/MypageMain.jsx
  front/src/pages/user/mypage/SaleHistory.jsx
  front/src/pages/user/mypage/buyHistory/BuyHistory.jsx
  front/src/styles/mypage.css
  front/src/styles/postcode.css
  front/src/styles/sub.css
Labels: 🖥️ FrontEnd, ✨ FEAT

#80 Front / fix : 프로필 수정 업로드 구현중
  front/src/pages/user/mypage/Modify.jsx
  front/src/pages/user/mypage/MypageMain.jsx
Labels: 🖥️ FrontEnd, 🛠FIX

#81 front/admin 수정
  front/src/api/admin/AdminLuckyApi.js
  front/src/api/admin/productApi.js
  front/src/pages/admin/AdminLuckydraws.jsx
  front/src/pages/admin/AdminProductDetailed.jsx
  front/src/pages/admin/AdminProducts.jsx
  front/src/pages/admin/AdminRequestDetailed.jsx
  front/src/pages/admin/LuckyDrawForm.jsx
  front/src/pages/admin/admin.css
  front/src/pages/admin/components/AdminLuckyDetail.jsx
Labels: 🖥️ FrontEnd

#82 Feat profile img
  front/src/api/user/userApi.jsx
  front/src/assets/images/WelshCorgi.jpeg
  front/src/hooks/useCustomRegister.jsx
  front/src/pages/admin/AdminRegister.jsx
  front/src/pages/admin/layout/UserProfile.jsx
  front/src/pages/user/Register.jsx
  front/src/pages/user/mypage/Modify.jsx
  front/src/pages/user/mypage/MypageMain.jsx
Labels: 🖥️ FrontEnd, ✨ FEAT

#83 Front / fix : 비밀번호 제외 프로필 수정시 재로그인 안되는 오류 수정
  front/src/pages/user/mypage/Modify.jsx
Labels: 🖥️ FrontEnd, ✨ FEAT

#85 front/라우터 수정
  front/src/api/admin/AdminLuckyApi.js
  front/src/api/admin/aMypageApi.js
  front/src/api/admin/requestApi.js
  front/src/pages/admin/AdminRequestDetailed.jsx
  front/src/pages/admin/layout/AdminSideBar.jsx
  front/src/pages/user/mypage/Account.jsx
  front/src/pages/user/mypage/SalesSummary.jsx
  front/src/router/AdminRouter.jsx
  front/src/styles/admin.css
  front/src/styles/sales.css
Labels: 🖥️ FrontEnd

#87 Front / feat: refresh토큰 기능 구현
  front/src/pages/user/jwtUtil.js
Labels: 🖥️ FrontEnd, ✨ FEAT

#88 Front / feat: 로그아웃 요청 추가
  front/src/api/user/userApi.jsx
  front/src/hooks/useCustomLogin.jsx
  front/src/store/slices/loginSlice.jsx
Labels: 🖥️ FrontEnd, ✨ FEAT

#89 Front / feat: 회원탈퇴 기능 추가
  front/src/api/user/userApi.jsx
  front/src/hooks/useCustomLogin.jsx
  front/src/pages/user/mypage/Modify.jsx
  front/src/store/slices/loginSlice.jsx
  front/src/styles/mypage.css
Labels: 🖥️ FrontEnd, ✨ FEAT

#90 front/admin 수정
  front/src/api/admin/aMypageApi.js
  front/src/pages/admin/AdminRequest.jsx
  front/src/pages/user/mypage/SalesSummary.jsx
  front/src/styles/sales.css
Labels: 🖥️ FrontEnd

#91 Front / fix: jwtAxios 인스턴스 속성 추가 및 api 엔드포인트 수정
  front/src/api/luckydrawApi.jsx
  front/src/api/user/mypageApi.jsx
  front/src/api/user/userApi.jsx
  front/src/pages/user/jwtUtil.js
Labels: 🖥️ FrontEnd, 🛠FIX

#95 front/admin 상품전체조회 수정
  front/src/api/admin/aMypageApi.js
  front/src/pages/admin/AdminLuckydraws.jsx
  front/src/pages/admin/AdminProducts.jsx
  front/src/pages/user/mypage/SalesSummary.jsx
Labels: 🖥️ FrontEnd

#96 front/admin 요청상품 페이지네이션 및 로그인 경로 수정
  front/src/api/admin/requestApi.js
  front/src/hooks/useCustomLogin.jsx
  front/src/pages/admin/AdminMain.jsx
  front/src/pages/admin/AdminProducts.jsx
  front/src/pages/admin/AdminRequest.jsx
  front/src/pages/admin/AdminRequestDetailed.jsx
  front/src/pages/admin/layout/UserProfile.jsx
  front/src/router/AdminRouter.jsx
Labels: 🖥️ FrontEnd

#97 front/admin 판매상품 페이지네이션 적용
  front/src/api/admin/productApi.js
  front/src/pages/admin/AdminProducts.jsx
  front/src/pages/admin/AdminRequest.jsx
Labels: 🖥️ FrontEnd

#99 front/mypage 정산 페이지네이션 수정
  front/src/pages/user/mypage/SalesSummary.jsx
  front/src/styles/sales.css
Labels: 🖥️ FrontEnd

#105 Front / 버튼 수정
  front/src/styles/sub.css
Labels: 🖥️ FrontEnd, 🛠FIX, 💡cicd

#107 Dev
  front/src/components/CouponDday.jsx
  front/src/components/mypage/MypageBookmark.jsx
  front/src/components/order/OrderAccountInfo.jsx
  front/src/components/order/OrderBuyNowProduct.jsx
  front/src/components/order/OrderBuyProduct.jsx
  front/src/components/order/OrderInfo.jsx
  front/src/components/order/OrderPaymentInfo.jsx
  front/src/components/order/OrderProdcutInfo.jsx
  front/src/components/order/OrderSaleNowProduct.jsx
  front/src/components/order/OrderSaleProduct.jsx
  front/src/components/order/OrderSeleInfo.jsx
  front/src/hooks/useBid.jsx
  front/src/pages/event/Event.jsx
  front/src/pages/ordres/Buy.jsx
  front/src/pages/ordres/Sell.jsx
  front/src/pages/payment/Success.jsx
  front/src/pages/product/ProductBid.jsx
  front/src/pages/product/ProductDetail.jsx
  front/src/pages/serviceCenter/inquiry/AdminInquiryDetailPage.css
  front/src/pages/serviceCenter/inquiry/AdminInquiryDetailTop.jsx
  front/src/pages/serviceCenter/inquiry/AdminInquiryItemList.jsx
  front/src/pages/serviceCenter/inquiry/AdminInquiryPage.css
  front/src/pages/serviceCenter/inquiry/AdminInquiryPage.jsx
  front/src/pages/serviceCenter/notice/AdminNotice.css
  front/src/pages/serviceCenter/notice/AdminNotice.jsx
  front/src/pages/serviceCenter/notice/AdminNoticeItem.jsx
  front/src/pages/serviceCenter/notice/AdminNoticeList.jsx
  front/src/pages/serviceCenter/notice/AdminNoticeTabs.jsx
  front/src/pages/serviceCenter/notice/LuckyDrawRegister.css
  front/src/pages/serviceCenter/notice/LuckyDrawRegister.jsx
  front/src/pages/serviceCenter/notice/NoticeList.jsx
  front/src/pages/serviceCenter/notice/NoticeRegistration.css
  front/src/pages/serviceCenter/notice/NoticeRegistration.jsx
  front/src/pages/serviceCenter/notice/NoticeRegistrationForm.jsx
  front/src/pages/user/mypage/BookmarkFeed.jsx
  front/src/styles/index.css
  front/src/styles/sub.css
Labels: 🚨 HOTFIX, 🖥️ FrontEnd, 💡cicd
